version: '3'

services:
    tinyurldb:
        image: postgres
        ports:
            - "5432:5432"
        expose:
            - "5432"

    tinyurlweb:
        build: .
        ports:
            - "8000:8000"
        depends_on:
            - tinyurldb
        command: ["./django-migrations.sh", "python", "manage.py", "runserver", "0.0.0.0:8000"]
        restart: on-failure
        volumes:
            - .:/code/